### PR TITLE
Speed optimisations for HiPERCAM pipeline

### PR DESCRIPTION
**Pull request by StuartLittlefair**
@trmrsh - I've made this pull request so we can have somewhere to comment on bugs in the ```faster``` branch. Any changes you make to that branch are automatically updated here, so we can merge this once you're happy.

### CODE REVIEW

**Comment by StuartLittlefair** [comment]
rtplot bug: when plotting from server

```
run - run name [run0003]: 
first - first frame to plot [0]: 1
ccd - CCD(s) to plot [0 for all] [0]: \
1, utc = 2018-11-14 17:07:20.803, ccd 1: -8.0, 8.0, exp: 0.0000, ccd 2: -8.0, 9.0, exp: 0.0000, ccd 3: -9.0, 9.0, exp: 0.0000, ccd 4: -8.0, 8.0, exp: 0.0000, ccd 5: -8.0, 8.0, exp: 0.0000
Traceback (most recent call last):
  File "/Users/sl/anaconda3/bin/rtplot", line 11, in <module>
    sys.exit(rtplot())
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/rtplot.py", line 504, in rtplot
    for mccd in spool:
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/spooler.py", line 274, in __next__
    return self._iter.__next__()
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/hcam.py", line 790, in __next__
    return self.__call__()
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/hcam.py", line 1018, in __call__
    (self.nframe % ch['NCYCLE'] == 0),
ZeroDivisionError: integer division or modulo by zero
```

**Comment by trmrsh** [comment]
damn, complicated this -- I just pushed some fixes that could already have solved this. Can you pull and check whether it still applies?

**Comment by StuartLittlefair** [comment]
tracked this down to a problem with ```ccd.is_data()``` which itself just looks up the ```DSTATUS``` for a ```CCD``` object. This is being set to False for all except the first frame.

**Comment by StuartLittlefair** [comment]
New bug - optimal extraction does not work. 

Need to import ```fitting``` and ```warnings```, but after that we have:

```python
Frame 1: 2018-11-14T19:24:22.888425270 [NOK]
Frame 2: 2018-11-14T19:24:22.934983850 [NOK]
Frame 3: 2018-11-14T19:24:22.981542430 [NOK]
Frame 4: 2018-11-14T19:24:23.028101010 [NOK]
Frame 5: 2018-11-14T19:24:23.074659590 [NOK]
Frame 6: 2018-11-14T19:24:23.121218170 [NOK]
Frame 7: 2018-11-14T19:24:23.167776750 [NOK]
Frame 8: 2018-11-14T19:24:23.214335335 [NOK]
/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py:911: UserWarning: Transmission plot is not reliable with optimal extraction
  'Transmission plot is not reliable'
/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py:911: UserWarning: Transmission plot is not reliable with optimal extraction
  'Transmission plot is not reliable'
/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py:911: UserWarning: Transmission plot is not reliable with optimal extraction
  'Transmission plot is not reliable'
/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py:911: UserWarning: Transmission plot is not reliable with optimal extraction
  'Transmission plot is not reliable'
/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py:911: UserWarning: Transmission plot is not reliable with optimal extraction
  'Transmission plot is not reliable'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/sl/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sl/anaconda3/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py", line 587, in ccdproc
    cnam, ccd, rccd, read, gain, ccdwin, rfile, store
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py", line 926, in extractFlux
    rfile['apertures']['fit_ndiv']
TypeError: not enough arguments: expected 10, got 9
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sl/anaconda3/bin/reduce", line 11, in <module>
    sys.exit(reduce())
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/scripts/reduce.py", line 496, in reduce
    results = processor(pccds, mccds, nframes)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hipercam/reduction.py", line 1239, in __call__
    allres = self.pool.starmap(self.ccdproc, arglist)
  File "/Users/sl/anaconda3/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/sl/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: not enough arguments: expected 10, got 9
```

**Comment by StuartLittlefair** [comment]
Also, an error with ```grab``` that has been introduced because of the move to a new header class. FITS headers can be indexed by key or card index (integer), but the ```hipercam.header.Header``` object can only be indexed by key, so it can't be added to an astropy ```HDUList```.

**Comment by trmrsh** [comment]
Thanks Stu, a "few" bugs then. Can I check that the rtplot one occurs when accessing the server in particular (it seems OK on a file)? Sorry for delay. I found I could not install numba on my laptop and ended up installing miniconda, a saga in itself, which also prompted me to switch from tcsh to bash (!) I'll get working on the others tomorrow I hope. Glad we haven't tried merging yet.

**Comment by trmrsh** [comment]
Ahhhhh! superb spotting the list default argument problem.

**Comment by StuartLittlefair** [comment]
I've now fixed the optimal extraction and grab bugs...

**Comment by trmrsh** [comment]
ah cheers stu. I just spotted you had done some fixes and pulled them back to here. will pick up things tomorrow

**Comment by trmrsh** [comment]
By the way, you may have spotted it, but one of the changes I made was to allow frames to be processed in batches ("ngroup" in the reduce file). This reduces parallelisation overheads, especially for small formats.

**Comment by StuartLittlefair** [comment]
```psf_reduce``` looks like it isn't using the new ```ProcessCCDs``` class

**Pull request merged**
